name: hapind
description: Created by - The Flutter Way

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  flutter_svg: ^2.0.7 # help us to use SVG in our app
  provider: ^6.0.5 # for State management
  carousel_slider: ^4.2.1
  swipe_cards: ^2.0.0+1
  http: ^1.1.0
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.6.0
  story: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  faker: ^2.1.0
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  datetime_picker_formfield: ^2.0.1
  sqflite: ^2.3.2
  path: ^1.9.0
  geolocator: ^11.0.0
  baseflow_plugin_template: ^2.1.2
  google_maps_flutter: ^2.5.3
  json_annotation: ^4.8.1
  quickalert: ^1.0.2
  image_picker: ^1.0.7
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.5.0
  cloud_firestore: ^4.15.5
  firebase_messaging: ^14.7.16
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_lints: ^2.0.0
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_laucher_icons:
ardroid: "icon"
ios: true
image_path: "assets/icons/icon.png"
min_sdk_android: 21
removi_alpha_ios: true


   
