// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Uwi_93-flMvhM_3Qz-boPaS2A2m5fXg',
    appId: '1:155876045339:web:3a5016ab9292681f4ebebe',
    messagingSenderId: '155876045339',
    projectId: 'chatmessenger-a9328',
    authDomain: 'chatmessenger-a9328.firebaseapp.com',
    storageBucket: 'chatmessenger-a9328.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGqHhujiThqX8I0otT_h3qfqpbrileHk',
    appId: '1:155876045339:android:ea8afb8812e5727e4ebebe',
    messagingSenderId: '155876045339',
    projectId: 'chatmessenger-a9328',
    storageBucket: 'chatmessenger-a9328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Hvdl8nFMPPhAyHs8zkB3yZLLrCpD9aQ',
    appId: '1:155876045339:ios:f24aae19a64a305b4ebebe',
    messagingSenderId: '155876045339',
    projectId: 'chatmessenger-a9328',
    storageBucket: 'chatmessenger-a9328.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Hvdl8nFMPPhAyHs8zkB3yZLLrCpD9aQ',
    appId: '1:155876045339:ios:6ca2ed0d1299e2814ebebe',
    messagingSenderId: '155876045339',
    projectId: 'chatmessenger-a9328',
    storageBucket: 'chatmessenger-a9328.appspot.com',
    iosBundleId: 'com.example.group01.RunnerTests',
  );
}
